openapi: 3.0.1
info:
  title: API Sentence Generator - Animals service only
  description: list of attributes for Animals
  version: v3
paths:
  /:
    get:
      description: List all animals
      tags:
        - animals
      responses:
        '200':
          description: a list of animals with their index
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Animals"
    post:
      description: create an animal
      tags:
        - animals
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            example:
              name: cat
      responses:
        '201':
          description: animal created
          content:
            application/json:
              schema:
                type: object
                properties: 
                  id:
                    type: integer
                  name:
                    type: string
              example:
                id: 4
                name: cat
  /{id}:
    get:
      description: get a specific adjective
      tags:
        - animals
      parameters:
        - name: id
          in: path
          required: true
          description: id of the animal to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties: 
                  id:
                    type: integer
                  name:
                    type: string
              example:
                id: 4
                name: cat
    delete:
      description: delete an adjective
      tags:
        - animals
      parameters:
        - name: id
          in: path
          required: true
          description: id of the animal to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Delete an Adjective
          content:
            application/json:
              schema:
                type: object
              example: {}
components:
  schemas:
    Animals:
      type: array
      items:
        required:
          - name
        properties:
          id:
            type: integer
            format: int64
            example: 1
          name:
            type: string
            example: cat

servers:
  - url: http://animals
