openapi: 3.0.1
info:
  title: API Sentence Generator - Locations service only
  description: list of attributes for Locations
  version: v3
paths:
  /locations:
    get:
      description: List all locations
      tags:
        - locations
      responses:
        '200':
          description: a list of locations with their index
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Locations"
    post:
      description: create a location
      tags:
        - locations
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                coordinates:
                  type: array
                  items:
                    type: integer
                    format: int64
            example:
              name: lake
              coordinates: -142.28261413,53.28261413
      responses:
        '201':
          description: location created
          content:
            application/json:
              schema:
                type: object
                properties: 
                  id:
                    type: integer
                  name:
                    type: string
                  coordinates:
                    type: array
                    items:
                      type: integer
                      format: int64
              example:
                id: 4
                name: lake
                coordinates: -142.28261413,53.28261413
  /locations/{id}:
    get:
      description: get a specific location
      tags:
        - locations
      parameters:
        - name: id
          in: path
          required: true
          description: id of the location to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties: 
                  id:
                    type: integer
                  name:
                    type: string
                  coordinates:
                    type: array
                    items:
                      type: integer
                      format: int64
              example:
                id: 4
                name: lake
                coordinates: -142.28261413,53.28261413
    delete:
      description: delete a location
      tags:
        - locations
      parameters:
        - name: id
          in: path
          required: true
          description: id of the location to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Delete a Location
          content:
            application/json:
              schema:
                type: object
              example: {}

components:
  schemas:
    Locations:
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: lake
        coordinates:
          type: array
          items:
            type: integer
            format: int64
          example: -142.28261413,53.28261413
servers:
  - url: http://locations
